package com.dbroslegion.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity Product composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author ychen
 */
@Entity
@Table(name = "product")
public class Product {
 
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  @NotNull
  private String prodid;

  @NotNull
  private String prodname;

  private String prodtype;
  
  private String updated;

  protected Product() { }

  public Product(String prodid, String prodname, String prodtype, String updated) {
    this.prodid = prodid;
    this.prodname = prodname;
    this.prodtype = prodtype;
    this.updated = updated;
  }
  
  	public String getProdid() {
  		return prodid;
	}
	
	public void setProdid(String prodid) {
		this.prodid = prodid;
	}
	
	public String getProdname() {
		return prodname;
	}
	
	public void setProdname(String prodname) {
		this.prodname = prodname;
	}
	
	public String getProdtype() {
		return prodtype;
	}
	
	public void setProdtype(String prodtype) {
		this.prodtype = prodtype;
	}
	
	public String getUpdated() {
		return updated;
	}
	
	public void setUpdated(String updated) {
		this.updated = updated;
	}

	  @Override
	  public String toString() {
		  return "id=" + Long.toString(id)  + ";prodid=" + this.prodid + ";prodname=" + prodname + ";prodtype=" + this.prodtype + ";updated=" + updated;
	  }
	  	
  
}
